version: 2
updates:
    # Update Maven dependencies
    - package-ecosystem: "maven"
      directory: "/"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10
      reviewers:
          - "yev"

    # Update GitHub Actions dependencies
    - package-ecosystem: "github-actions"
      directory: "/.github/workflows"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 5
