###
POST http://localhost:8080/todos
Content-Type: application/json

{
    "title": "hello yev Python",
    "isCompleted": true
}

###
GET http://localhost:8080/todos/search?title=yev

### modify existing todo
PATCH  http://localhost:8080/todos
Content-Type: application/json

{
    "id": 1102,
    "title": "modified todo",
    "isCompleted": true
}

