openapi: 3.0.0
info:
    title: Todo Application API
    version: 1.0.0-SNAPSHOT
    description: A simple API for managing todos
    contact:
        email: yev@devatlant.com
        name: Yevgen Voronetski
        url: https://devatlant.com

servers:
    - url: http://localhost:8080

components:
    schemas:
        ToDoDto:
            type: object
            required:
                - title
                - isCompleted
            properties:
                title:
                    type: string
                    description: title
                    example: "my title"
                isCompleted:
                    type: boolean
                    description: is this todo item is done
                    example: true
        ApiErrorItem:
            type: object
            required:
                - name
                - errorDescription
                - gitId
            properties:
                name:
                    type: string
                errorDescription:
                    type: string
                gitId:
                    type: string

        ApiError:
            type: array
            items:
                $ref: "#/components/schemas/ApiErrorItem"


paths:
    /todos:
        post:
            summary: Create a new todo
            operationId: createTodo
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ToDoDto"
            responses:
                '201':
                    description: Todo created successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ToDoDto"
                '400':
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ApiError"

    /todos/{id}:
        get:
            summary: Retrieve a todo by ID
            operationId: getTodoById
            parameters:
                - name: id
                  in: path
                  required: true
                  description: The ID of the todo to retrieve
                  schema:
                      type: integer
            responses:
                '200':
                    description: Todo retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ToDoDto"
                '404':
                    description: Todo not found

    /todos/search:
        get:
            summary: Search todos by title
            operationId: searchTodosByTitle
            parameters:
                - name: title
                  in: query
                  required: true
                  description: The title of the todo to search for
                  schema:
                      type: string
            responses:
                '200':
                    description: List of todos matching the search criteria
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/ToDoDto'
